name: Publish release as Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: bootBuildImage
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Define image name for docker hub
        run: echo "imageName=${{ secrets.DOCKER_HUB_USERNAME }}/$(echo ${{ github.repository }} | sed 's/.*\///')" >> $GITHUB_ENV
      - name: Push with current tag to docker hub
        run: docker push ${{ env.imageName }}:${{ github.event.release.tag_name }}
      - name: Tag this image as latest
        run: docker image tag ${{ env.imageName }}:${{ github.event.release.tag_name }} ${{ env.imageName }}:latest 
      - name: Also push as latest
        run: docker push ${{ env.imageName }}:latest       